// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_welcome = "CgkIlNKumJAHEAIQCg"; // <GPGSID>
        public const string achievement_the_first_battle = "CgkIlNKumJAHEAIQCA"; // <GPGSID>
        public const string leaderboard_thebesplayers = "CgkIlNKumJAHEAIQAg"; // <GPGSID>
        public const string achievement_my_golden_vault = "CgkIlNKumJAHEAIQBw"; // <GPGSID>
        public const string achievement_my_gold = "CgkIlNKumJAHEAIQBg"; // <GPGSID>
        public const string achievement_lose_everything = "CgkIlNKumJAHEAIQBA"; // <GPGSID>
        public const string achievement_hum_from_space = "CgkIlNKumJAHEAIQCQ"; // <GPGSID>
        public const string achievement_all_mine = "CgkIlNKumJAHEAIQBQ"; // <GPGSID>

}

